TestBeds:
  - Name: EnterpriseTestBed
    Controllers:
      AndroidDevice:
        - serial: emulator-5554

UserParams:
  wifi_ssid: "NoneExistWifi"
  wifi_pwd: ""
  target_app_pkg: "mobly_test.apk"
  test_app_path: "tests/test_data/apks/mobly_test.apk"